/**
 * finding-parser.mjs
 *
 * Parses heterogeneous genealogy finding markdown files generated by Claude's
 * FamilySearch research pipeline. Returns structured data for use by downstream
 * scripts (record promotion, key-facts derivation, etc.).
 *
 * Supports the two main finding formats:
 *   1. Structured format: `- **Field:** value` bullet metadata + `### Record N:` sections
 *   2. Loose format: `**Field:** value` inline metadata + `### Record N:` sections
 */

import { normalizeFieldName } from './field-normalizer.mjs';

// ---------------------------------------------------------------------------
// Type definitions (JSDoc only — no TypeScript)
// ---------------------------------------------------------------------------

/**
 * @typedef {Object} ParsedRecord
 * @property {string|null} ark            - Raw ARK value (URL, short form, or null if invalid/absent)
 * @property {string|null} tier           - Single letter tier (A–E) or null
 * @property {string|null} collection     - Collection name or null
 * @property {string|null} recordType     - Inferred or explicit record type
 * @property {boolean}     isTreeOnly     - True when collection is a user-contributed tree
 * @property {Map<string,string>} fields  - Normalised field name → value
 * @property {object[]}    household      - Rows from the Household table (census records)
 * @property {string}      rawContent     - The raw section text
 */

/**
 * @typedef {Object} NotFoundSection
 * @property {string} rawText  - Raw text of the NOT FOUND section
 */

/**
 * @typedef {Object} FindingResult
 * @property {string|null}      personSlug  - Slug identifying the subject person
 * @property {string|null}      searchDate  - YYYY-MM-DD of the research session
 * @property {string|null}      taskType    - Task type suffix (census, death_record, etc.)
 * @property {ParsedRecord[]}   records     - One per ### Record N section
 * @property {NotFoundSection[]} notFound   - Extracted NOT FOUND sections
 */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Collection names that indicate a FamilySearch user-contributed tree entry. */
const TREE_COLLECTION_PATTERNS = [
  /familysearch family tree/i,
  /family search family tree/i,
  /^family tree$/i,
];

/** Infer record type from collection name. */
const COLLECTION_TYPE_MAP = [
  [/census/i,     'census'],
  [/death/i,      'death'],
  [/marriage/i,   'marriage'],
  [/burial/i,     'burial'],
  [/find a grave/i, 'burial'],
  [/birth/i,      'birth'],
  [/military/i,   'military'],
  [/immigration/i,'immigration'],
  [/probate/i,    'probate'],
  [/land/i,       'land'],
];

/** ARK values that should be treated as null (not a real record identifier). */
const INVALID_ARK_PATTERNS = [
  /^\(/, // starts with '(' — placeholder text
  /^none$/i,
  /^n\/a$/i,
  /^-$/,
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Return true if the raw ARK string is a valid identifier.
 * @param {string} raw
 * @returns {boolean}
 */
function isValidArk(raw) {
  if (!raw || !raw.trim()) return false;
  const trimmed = raw.trim();
  return !INVALID_ARK_PATTERNS.some((p) => p.test(trimmed));
}

/**
 * Infer record type from collection name.
 * @param {string|null} collection
 * @returns {string|null}
 */
function inferRecordType(collection) {
  if (!collection) return null;
  for (const [pattern, type] of COLLECTION_TYPE_MAP) {
    if (pattern.test(collection)) return type;
  }
  return null;
}

/**
 * Return true if the collection name indicates a user-contributed tree.
 * @param {string|null} collection
 * @param {string|null} tier
 * @returns {boolean}
 */
function isTreeOnlyCollection(collection, tier) {
  if (!collection) return false;
  if (TREE_COLLECTION_PATTERNS.some((p) => p.test(collection))) return true;
  // Tier D or E with "tree" anywhere in collection name is treated as tree-only
  if ((tier === 'D' || tier === 'E') && /tree/i.test(collection)) return true;
  return false;
}

/**
 * Parse a markdown table into an array of objects.
 * The first non-separator row is the header; subsequent rows become objects.
 * Handles 2-column (Field|Value) and 3-column (Field|Value|Verbatim) tables.
 *
 * @param {string} tableText
 * @returns {Array<{[key:string]: string}>}
 */
function parseMarkdownTable(tableText) {
  const lines = tableText
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);

  if (lines.length < 2) return [];

  // Split a pipe-delimited row into cell values (trim each cell).
  const splitRow = (line) =>
    line
      .replace(/^\|/, '')
      .replace(/\|$/, '')
      .split('|')
      .map((c) => c.trim());

  const headers = splitRow(lines[0]);

  const rows = [];
  for (let i = 1; i < lines.length; i++) {
    // Skip separator rows (contain only dashes, pipes, colons).
    if (/^[\|\-\:\s]+$/.test(lines[i])) continue;
    const cells = splitRow(lines[i]);
    const row = {};
    headers.forEach((h, idx) => {
      row[h] = cells[idx] ?? '';
    });
    rows.push(row);
  }
  return rows;
}

/**
 * Parse a two-column (Field|Value) or three-column (Field|Value|Verbatim) table
 * into a Map<normalizedField, value>.
 *
 * @param {string} tableText
 * @returns {Map<string,string>}
 */
function parseFieldTable(tableText) {
  const rows = parseMarkdownTable(tableText);
  const fields = new Map();
  for (const row of rows) {
    // Column names may be "Field"/"Value" or variations
    const rawField = row['Field'] ?? row['field'] ?? Object.values(row)[0] ?? '';
    const value = row['Value'] ?? row['value'] ?? Object.values(row)[1] ?? '';
    if (rawField) {
      fields.set(normalizeFieldName(rawField), value);
    }
  }
  return fields;
}

/**
 * Extract the text of a household table from a record section.
 * Looks for "#### Household" subsection.
 *
 * @param {string} sectionText
 * @returns {object[]}
 */
function parseHouseholdTable(sectionText) {
  const householdMatch = sectionText.match(/####\s+Household[^\n]*\n([\s\S]*?)(?=\n#{1,4}\s|\n\n##|$)/i);
  if (!householdMatch) return [];
  return parseMarkdownTable(householdMatch[1].trim());
}

/**
 * Extract the text of a contacts table from a record section.
 * Looks for "#### Contacts" subsection. Used by draft card records to
 * capture nearest-relative, next-of-kin, employer references, and other
 * non-household related persons. Roles are arbitrary text strings (Brother,
 * Friend, Landlady, Physician, Witness) — not constrained to household roles.
 *
 * @param {string} sectionText
 * @returns {object[]}
 */
function parseContactTable(sectionText) {
  const contactsMatch = sectionText.match(/####\s+Contacts[^\n]*\n([\s\S]*?)(?=\n#{1,4}\s|\n\n##|$)/i);
  if (!contactsMatch) return [];
  return parseMarkdownTable(contactsMatch[1].trim());
}

/**
 * Extract inline field tables that appear directly in a record section (without
 * an "#### Extracted Fields" / "#### Extracted Data" header). These are bare
 * pipe-tables in the middle of the section.
 *
 * @param {string} sectionText
 * @returns {Map<string,string>}
 */
function parseInlineFieldTable(sectionText) {
  // Find the first bare table block (not under #### Household)
  // A table block: consecutive lines starting with '|'
  const tableBlockPattern = /^(\|.+\|)\s*$/gm;
  const tableLines = [];
  let collecting = false;
  let inHousehold = false;

  for (const line of sectionText.split('\n')) {
    if (/^#{4}\s+household/i.test(line.trim())) {
      inHousehold = true;
      if (tableLines.length) break; // we had a table before household — done
      continue;
    }
    if (/^#{4}/.test(line.trim()) && inHousehold) {
      inHousehold = false;
      continue;
    }
    if (inHousehold) continue;

    if (line.trim().startsWith('|')) {
      tableLines.push(line.trim());
      collecting = true;
    } else if (collecting) {
      // End of table block
      break;
    }
  }

  if (!tableLines.length) return new Map();
  return parseFieldTable(tableLines.join('\n'));
}

// ---------------------------------------------------------------------------
// Record section parser
// ---------------------------------------------------------------------------

/**
 * Parse a single "### Record N" section into a ParsedRecord.
 *
 * @param {string} sectionText - Text of the record section (without the ### header line)
 * @returns {ParsedRecord}
 */
function parseRecordSection(sectionText) {
  // --- ARK ---
  // Formats:
  //   - **ARK**: https://...          (colon outside bold)
  //   - **ARK:** https://...          (colon inside bold)
  const arkMatch = sectionText.match(/\*\*ARK:?\*\*:?\s*([^\n]+)/i);
  let ark = arkMatch ? arkMatch[1].trim() : null;
  // Handle markdown link format: [SHORT](https://...ark...) → extract URL
  if (ark) {
    const mdLinkMatch = ark.match(/\[.*?\]\((https?:\/\/[^)]+)\)/);
    if (mdLinkMatch) {
      ark = mdLinkMatch[1];
    }
  }
  if (ark && !isValidArk(ark)) ark = null;

  // --- Tier ---
  // Formats:
  //   - **Tier**: B (federal census)
  //   - **Tier:** B
  //   - **Tier:** B (some annotation)  → take only the first letter
  const tierMatch = sectionText.match(/\*\*Tier:?\*\*:?\s*([A-E])/i);
  const tier = tierMatch ? tierMatch[1].toUpperCase() : null;

  // --- Collection ---
  const collectionMatch = sectionText.match(/\*\*Collection:?\*\*:?\s*([^\n]+)/i);
  const collection = collectionMatch ? collectionMatch[1].trim() : null;

  // --- Record Type ---
  const recordTypeMatch = sectionText.match(/\*\*Record Type:?\*\*:?\s*([^\n]+)/i);
  let recordType = recordTypeMatch ? recordTypeMatch[1].trim().toLowerCase() : null;
  if (!recordType) recordType = inferRecordType(collection);

  // --- isTreeOnly ---
  const isTreeOnly = isTreeOnlyCollection(collection, tier);

  // --- Fields ---
  // Look for explicit #### Extracted Fields / #### Extracted Data subsection.
  const extractedSectionMatch = sectionText.match(
    /####\s+(?:Extracted\s+(?:Fields|Data))\s*\n([\s\S]*?)(?=\n####|\n###|\n##|$)/i
  );

  let fields;
  if (extractedSectionMatch) {
    fields = parseFieldTable(extractedSectionMatch[1].trim());
  } else {
    // Fall back to an inline table in the record body.
    fields = parseInlineFieldTable(sectionText);
  }

  // --- Household ---
  const household = parseHouseholdTable(sectionText);

  // --- Contacts (draft cards, pensions, etc.) ---
  const contacts = parseContactTable(sectionText);

  return {
    ark,
    tier,
    collection,
    recordType,
    isTreeOnly,
    fields,
    household,
    contacts,
    rawContent: sectionText,
  };
}

// ---------------------------------------------------------------------------
// Metadata extraction
// ---------------------------------------------------------------------------

/**
 * Known task type suffixes, matched longest-first.
 * Each entry: [suffixToStrip, canonicalTaskType]
 *
 * Year-specific census tasks like "1950_census" normalize to taskType "census"
 * while stripping both the year and "census" suffix from the slug.
 */
const TASK_TYPE_SUFFIXES = [
  // Non-census specific records
  ['death_record',      'death_record'],
  ['marriage_record',   'marriage_record'],
  ['burial_record',     'burial_record'],
  ['birth_record',      'birth_record'],
  ['find_parents',      'find_parents'],
  ['source_assessment', 'source_assessment'],
  // Military draft cards (Phase 1 of military sweep)
  ['wwi_draft',         'military_draft'],
  ['wwii_1940_draft',   'military_draft'],
  ['wwii_1942_draft',   'military_draft'],
  ['wwii_1947_draft',   'military_draft'],
];

// Census years to handle (YYYY_census → "census")
const CENSUS_YEARS = ['2020','2010','2000','1990','1980','1970','1960','1950','1940','1930','1920','1910','1900','1880','1870','1860','1850','1840','1830'];

/**
 * Given a Queue Task ID string, derive (personSlug, taskType).
 *
 * @param {string} taskId
 * @returns {{ personSlug: string, taskType: string|null }}
 */
function deriveFromTaskId(taskId) {
  const id = taskId.trim();

  // Check year-specific census patterns first: foo_1950_census → slug=foo, type=census
  for (const year of CENSUS_YEARS) {
    const yearSuffix = `_${year}_census`;
    if (id.endsWith(yearSuffix)) {
      return {
        personSlug: id.slice(0, -yearSuffix.length),
        taskType: 'census',
      };
    }
  }

  // Plain census suffix: foo_census
  if (id.endsWith('_census')) {
    return {
      personSlug: id.slice(0, -'_census'.length),
      taskType: 'census',
    };
  }

  for (const [suffix, taskType] of TASK_TYPE_SUFFIXES) {
    if (id.endsWith(`_${suffix}`)) {
      return {
        personSlug: id.slice(0, -(suffix.length + 1)),
        taskType,
      };
    }
  }

  // No known suffix — return the whole ID as slug
  return { personSlug: id, taskType: null };
}

/**
 * Extract metadata from the top section of a finding markdown file.
 *
 * @param {string} headerText - First ~20 lines of the document
 * @returns {{ personSlug: string|null, searchDate: string|null, taskType: string|null }}
 */
function extractMetadata(headerText) {
  let personSlug = null;
  let searchDate = null;
  let taskType = null;

  // --- Verified node (explicit slug) ---
  // Formats:
  //   **Verified node:** slug    (colon inside bold)
  //   **Verified node**: slug    (colon outside bold)
  const verifiedNodeMatch = headerText.match(/\*\*Verified node:?\*\*:?\s*(\S+)/i);
  if (verifiedNodeMatch) {
    personSlug = verifiedNodeMatch[1].trim();
  }

  // --- Task type (explicit) ---
  // Formats:
  //   **Task type:** death_record
  //   **Task type**: death_record
  const taskTypeMatch = headerText.match(/\*\*Task type:?\*\*:?\s*(\S+)/i);
  if (taskTypeMatch) {
    taskType = taskTypeMatch[1].trim();
  }

  // --- Queue Task ID (from bullet list or HTML comment) ---
  // Formats:
  //   - **Queue ID**: mary_duff_1950_census
  //   - **Queue Task ID**: edwin_g_reed_death_record
  //   - <!-- ... | Queue Task: john_mitchell_micek_marriage_record -->
  const queueIdMatch = headerText.match(
    /\*\*Queue(?:\s+Task)?\s+ID:?\*\*:?\s*(\S+)/i
  );
  const commentTaskMatch = headerText.match(/Queue Task:\s+(\S+)/i);

  const rawTaskId = (queueIdMatch?.[1] ?? commentTaskMatch?.[1] ?? '').trim();

  if (rawTaskId && !personSlug) {
    const derived = deriveFromTaskId(rawTaskId);
    personSlug = derived.personSlug;
    if (!taskType) taskType = derived.taskType;
  } else if (rawTaskId && !taskType) {
    // We have a slug from verified node, but still want taskType from Queue ID
    const derived = deriveFromTaskId(rawTaskId);
    if (!taskType) taskType = derived.taskType;
  }

  // --- Search Date ---
  // Formats:
  //   - **Search Date**: 2026-03-09
  //   - **Search date:** 2026-02-28
  //   - <!-- Generated by ... | 2026-03-10 | ... -->
  const searchDateMatch = headerText.match(/\*\*Search\s+[Dd]ate:?\*\*:?\s*([\d]{4}-[\d]{2}-[\d]{2})/);
  if (searchDateMatch) {
    searchDate = searchDateMatch[1];
  } else {
    // Try HTML comment date
    const commentDateMatch = headerText.match(/<!--[^>]*?(\d{4}-\d{2}-\d{2})[^>]*?-->/);
    if (commentDateMatch) {
      searchDate = commentDateMatch[1];
    }
  }

  return { personSlug, searchDate, taskType };
}

// ---------------------------------------------------------------------------
// NOT FOUND parser
// ---------------------------------------------------------------------------

/**
 * Parse the NOT FOUND section of a finding into NotFoundSection entries.
 *
 * @param {string} content  - Full document text
 * @returns {NotFoundSection[]}
 */
function parseNotFound(content) {
  // Find the position of ## NOT FOUND
  const notFoundIdx = content.search(/^##\s+NOT FOUND/im);
  if (notFoundIdx === -1) return [];

  // Grab everything after the ## NOT FOUND header line
  const afterHeader = content.slice(notFoundIdx).replace(/^[^\n]+\n/, '');

  // Find the next top-level (## or #) section, if any
  const nextSectionIdx = afterHeader.search(/^##?\s+\S/m);
  const body = (nextSectionIdx === -1 ? afterHeader : afterHeader.slice(0, nextSectionIdx)).trim();

  if (!body) return [];

  // If there are ### sub-sections, split on them.
  const subSections = body.split(/^###\s+/m).filter(Boolean);
  if (subSections.length > 1) {
    return subSections.map((s) => ({ rawText: s.trim() }));
  }

  // Otherwise treat the whole body as one entry.
  return [{ rawText: body }];
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/**
 * Parse a finding markdown file and return structured data.
 *
 * @param {string} content - Raw markdown content of the finding file
 * @returns {FindingResult}
 */
export function parseFinding(content) {
  // Extract metadata from the first ~25 lines.
  const headerLines = content.split('\n').slice(0, 25).join('\n');
  const { personSlug, searchDate, taskType } = extractMetadata(headerLines);

  // --- Split into record sections ---
  // Split on "### Record N" (with optional subtitle).
  // We also need to handle the "## NOT FOUND" boundary.
  //
  // Strategy:
  //   1. Strip the NOT FOUND section and everything after it for record parsing.
  //   2. Split the remaining content on /^### Record \d+/m.

  // Find NOT FOUND boundary
  const notFoundIdx = content.search(/^##\s+NOT FOUND/im);
  const recordsContent = notFoundIdx === -1 ? content : content.slice(0, notFoundIdx);

  // Split on ### Record N headers
  const recordSectionRegex = /^###\s+Record\s+\d+[^\n]*/im;
  const parts = recordsContent.split(recordSectionRegex);

  // parts[0] is content before the first ### Record — that's the preamble.
  // parts[1..] are the bodies of each record section.
  const recordBodies = parts.slice(1);

  let records;

  if (recordBodies.length === 0) {
    // No ### Record N headers found.
    // Only create an implicit record if there are real record indicators:
    //   - An ARK field
    //   - A Tier field
    // A bare table (without ARK/Tier) is NOT treated as a record — it may be from
    // metadata sections like "New People Discovered".
    const hasArkOrTier =
      /\*\*ARK:?\*\*/i.test(recordsContent) ||
      /\*\*Tier:?\*\*/i.test(recordsContent);

    if (hasArkOrTier) {
      // Treat the whole document (minus preamble) as one implicit record.
      // Use everything after the first ## header as the record body.
      const afterFirstSection = recordsContent.replace(/^#[^\n]+\n/, '').trim();
      records = [parseRecordSection(afterFirstSection)];
    } else {
      records = [];
    }
  } else {
    records = recordBodies.map((body) => parseRecordSection(body));
  }

  // --- NOT FOUND ---
  const notFound = parseNotFound(content);

  return { personSlug, searchDate, taskType, records, notFound };
}
